apiVersion: v1
kind: Service
metadata:
  name: {{ include "roder.fullname" . }}
  labels:
    {{- include "roder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "roder.selectorLabels" . | nindent 4 }}
