{{- if .Values.talos.enabled }}
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: {{ include "roder.fullname" . }}
  labels:
    {{- include "roder.labels" . | nindent 4 }}
spec:
  roles:
    {{- toYaml .Values.talos.roles | nindent 4 }}
{{- end }}
