//! Direct Talos machine API access using Talos's native in-cluster credentials.

use std::collections::HashMap;
use std::path::Path;

use base64::Engine;
use roder_core::{TalosMount, TalosNetworkInterface, TalosNode, TalosService};
use serde::Deserialize;
use talos_api_rs::api::machine::machine_service_client::MachineServiceClient;
use tonic::metadata::MetadataValue;
use tonic::transport::{Certificate, Channel, ClientTlsConfig, Endpoint, Identity};
use tonic::Request;

pub const IN_CLUSTER_CONFIG: &str = "/var/run/secrets/talos.dev/config";

#[derive(Debug, thiserror::Error)]
pub enum TalosError {
    #[error("failed to read Talos in-cluster config: {0}")]
    Io(#[from] std::io::Error),
    #[error("invalid Talos in-cluster config: {0}")]
    Config(String),
    #[error("Talos API transport error: {0}")]
    Transport(#[from] tonic::transport::Error),
    #[error("Talos API request failed: {0}")]
    Status(#[from] tonic::Status),
}

#[derive(Deserialize)]
struct Config {
    context: String,
    contexts: HashMap<String, Context>,
}

#[derive(Deserialize)]
struct Context {
    endpoints: Vec<String>,
    ca: String,
    crt: String,
    key: String,
}

pub struct Backend {
    connection: tokio::sync::RwLock<Connection>,
}

struct Connection {
    config: String,
    channel: Channel,
}

impl Backend {
    /// Connect using the config generated by a `talos.dev/v1alpha1 ServiceAccount`.
    pub async fn connect_in_cluster() -> Result<Option<Self>, TalosError> {
        let path = Path::new(IN_CLUSTER_CONFIG);
        if !path.exists() {
            return Ok(None);
        }

        let raw = std::fs::read_to_string(path)?;
        let channel = connect(&raw).await?;
        Ok(Some(Self {
            connection: tokio::sync::RwLock::new(Connection {
                config: raw,
                channel,
            }),
        }))
    }

    /// Fetch independent status groups concurrently through the in-cluster API proxy.
    pub async fn node(&self, node: &str) -> Result<TalosNode, TalosError> {
        let channel = self.current_channel().await?;
        let (version, services, mounts, network) = tokio::try_join!(
            Self::call(&channel, node, |mut c, r| async move { c.version(r).await }),
            Self::call(
                &channel,
                node,
                |mut c, r| async move { c.service_list(r).await }
            ),
            Self::call(&channel, node, |mut c, r| async move { c.mounts(r).await }),
            Self::call(&channel, node, |mut c, r| async move {
                c.network_device_stats(r).await
            }),
        )?;

        let version = version
            .messages
            .first()
            .and_then(|m| m.version.as_ref())
            .map(|v| v.tag.clone())
            .unwrap_or_default();
        let services = services
            .messages
            .into_iter()
            .flat_map(|m| m.services)
            .map(|s| TalosService {
                id: s.id,
                state: s.state,
                healthy: s.health.as_ref().is_some_and(|h| h.healthy),
                message: s.health.map(|h| h.last_message).unwrap_or_default(),
            })
            .collect();
        let mounts = mounts
            .messages
            .into_iter()
            .flat_map(|m| m.stats)
            .map(|m| TalosMount {
                filesystem: m.filesystem,
                mounted_on: m.mounted_on,
                size: m.size,
                available: m.available,
            })
            .collect();
        let interfaces = network
            .messages
            .into_iter()
            .flat_map(|m| m.devices)
            .map(|d| TalosNetworkInterface {
                name: d.name,
                rx_bytes: d.rx_bytes,
                tx_bytes: d.tx_bytes,
                rx_errors: d.rx_errors,
                tx_errors: d.tx_errors,
                rx_dropped: d.rx_dropped,
                tx_dropped: d.tx_dropped,
            })
            .collect();

        Ok(TalosNode {
            node: node.to_string(),
            version,
            services,
            mounts,
            interfaces,
        })
    }

    async fn current_channel(&self) -> Result<Channel, TalosError> {
        let raw = std::fs::read_to_string(IN_CLUSTER_CONFIG)?;
        {
            let current = self.connection.read().await;
            if current.config == raw {
                return Ok(current.channel.clone());
            }
        }

        let channel = connect(&raw).await?;
        let mut current = self.connection.write().await;
        if current.config != raw {
            current.config = raw;
            current.channel = channel;
        }
        Ok(current.channel.clone())
    }

    async fn call<T, F, Fut>(channel: &Channel, node: &str, call: F) -> Result<T, TalosError>
    where
        F: FnOnce(MachineServiceClient<Channel>, Request<()>) -> Fut,
        Fut: std::future::Future<Output = Result<tonic::Response<T>, tonic::Status>>,
    {
        let value: MetadataValue<_> = node
            .parse()
            .map_err(|_| TalosError::Config(format!("invalid node target {node:?}")))?;
        let mut request = Request::new(());
        request.metadata_mut().insert("x-talos-node", value);
        Ok(call(MachineServiceClient::new(channel.clone()), request)
            .await?
            .into_inner())
    }
}

async fn connect(raw: &str) -> Result<Channel, TalosError> {
    let config: Config =
        serde_yaml::from_str(raw).map_err(|e| TalosError::Config(format!("invalid YAML: {e}")))?;
    let context = config.contexts.get(&config.context).ok_or_else(|| {
        TalosError::Config(format!("context {:?} does not exist", config.context))
    })?;
    let endpoint = context
        .endpoints
        .first()
        .ok_or_else(|| TalosError::Config("active context has no endpoint".into()))?;
    let endpoint = if endpoint.contains("://") {
        endpoint.clone()
    } else if endpoint.contains(':') {
        format!("https://{endpoint}")
    } else {
        format!("https://{endpoint}:50000")
    };

    let ca = decode_config_value("ca", &context.ca)?;
    let crt = decode_config_value("crt", &context.crt)?;
    let key = decode_config_value("key", &context.key)?;
    let tls = ClientTlsConfig::new()
        .ca_certificate(Certificate::from_pem(ca))
        .identity(Identity::from_pem(crt, key));
    Endpoint::from_shared(endpoint)
        .map_err(|e| TalosError::Config(e.to_string()))?
        .tls_config(tls)?
        .connect()
        .await
        .map_err(TalosError::from)
}

fn decode_config_value(name: &str, value: &str) -> Result<Vec<u8>, TalosError> {
    if value.contains("-----BEGIN") {
        return Ok(value.as_bytes().to_vec());
    }
    base64::engine::general_purpose::STANDARD
        .decode(value.trim())
        .map_err(|e| TalosError::Config(format!("invalid base64 {name}: {e}")))
}
